name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g stylus
      - run: stylus -c style.styl -o ./public/style.css
      # Remove ignore for gh-pages to avoid ignoring public/style.css
      - run: rm .gitignore
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.graphguard.io
          publish_dir: ./public
